import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Confier votre toutou • Garde de chien Gratuite • Emprunte Mon Toutou',
  description: 'Generated by create next app',
};

export default async function EntrustYourDog() {
  return <div>EntrustYourDog</div>;
}
