import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "À propos d'Emprunte Mon Toutou  • Emprunte Mon toutou",
  description: 'Generated by create next app',
};

export default function OurStory() {
  return <div>OurStory</div>;
}
