import { Metadata } from 'next';
import { FirstSection } from '@/components/site/main_page/first-section';

export const metadata: Metadata = {
  title: 'Emprunte mon toutou • Partagez le bonheur des toutous !',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className=' flex flex-col overflow-hidden'>
      <FirstSection />
      <div className='mt-36 h-96 md:mt-12'></div>
    </main>
  );
}
