import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className='flex flex-col'>{children}</div>;
}
