import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Avis et témoignages • Emprunte Mon Toutou',
  description: 'Generated by create next app',
};

export default function Testimonials() {
  return <div>Testimonials</div>;
}
