import type { Metadata } from 'next';
import './globals.css';
import { nunito } from '@/styles/fonts';
import { Header } from '@/components/Header';
import { StickyPart } from '@/components/StickyPart';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={nunito.className}>
        <Header />
        <StickyPart />
        {children}
      </body>
    </html>
  );
}
