import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Emprunter un toutou • Emprunte Mon Toutou',
  description: 'Generated by create next app',
};

export default async function BorrowADoggo() {
  return <div>BorrowADoggo</div>;
}
