import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Confiance et sécurité • Emprunte Mon toutou',
  description: 'Generated by create next app',
};

export default async function TrustAndSecurity() {
  return <div>TrustAndSecurity</div>;
}
